//! Raw bindings to libplacebo (`vulkan.h`, `renderer.h`, `utils/libav.h`),
//! generated by bindgen at build time, and to two pieces of C compiled with
//! them: libplacebo's inline FFmpeg helpers (`src/libav.c`) and the device
//! the scene graph, libplacebo and FFmpeg's decoder share
//! (`src/shared_device.c`). Everything here is `unsafe`; the engine's `gpu`
//! and `shared_device` modules are the safe layer over it.

#![allow(
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    missing_debug_implementations,
    unsafe_op_in_unsafe_fn,
    clippy::all,
    clippy::pedantic,
    reason = "generated bindings keep C's names and shapes"
)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
