//! Raw bindings to libass (`ass/ass.h`), generated by bindgen at build time.
//! Everything here is `unsafe`; the engine's `subtitles` module is the safe
//! layer over it.

#![allow(
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    missing_debug_implementations,
    unsafe_op_in_unsafe_fn,
    clippy::all,
    clippy::pedantic,
    reason = "generated bindings keep C's names and shapes"
)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
