"""Port interfaces (Protocols) the application depends on and infrastructure implements."""

from __future__ import annotations

from collections.abc import Callable
from typing import Protocol, runtime_checkable

from gravitas.domain.models import (
    AddonManifest,
    CatalogRef,
    MediaItem,
    MediaType,
    MetaDetail,
    PersistedSettings,
    ResolvedMedia,
    Stream,
    SubtitleStyle,
)


@runtime_checkable
class AddonSource(Protocol):
    async def fetch_manifest(self, url: str) -> AddonManifest: ...
    async def fetch_catalog(
        self,
        manifest: AddonManifest,
        ref: CatalogRef,
        *,
        genre: str | None = None,
        skip: int = 0,
        search: str | None = None,
    ) -> list[MediaItem]: ...
    async def fetch_meta(self, manifest: AddonManifest, type: MediaType, id: str) -> MetaDetail: ...
    async def fetch_streams(
        self, manifest: AddonManifest, type: MediaType, id: str
    ) -> list[Stream]: ...


@runtime_checkable
class Cache(Protocol):
    async def get_or_fetch(self, url: str) -> bytes: ...


@runtime_checkable
class MediaPlayer(Protocol):
    def play(self, url: str) -> None: ...
    def stop(self) -> None: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    def is_paused(self) -> bool: ...
    def seek(self, seconds: float) -> None: ...
    def position(self) -> float: ...
    def duration(self) -> float: ...
    def set_volume(self, volume: float) -> None: ...
    def volume(self) -> float: ...
    def set_muted(self, muted: bool) -> None: ...
    def is_muted(self) -> bool: ...
    def is_loading(self) -> bool:
        """True while playback is stalled on I/O (buffering or seeking)."""
        ...

    def set_subtitle_track(self, track_id: int | None) -> None: ...
    def subtitle_tracks(self) -> list[tuple[int, str]]: ...
    def set_audio_track(self, track_id: int | None) -> None: ...
    def audio_tracks(self) -> list[tuple[int, str]]: ...
    def current_subtitle_track(self) -> int | None: ...
    def current_audio_track(self) -> int | None: ...
    def apply_subtitle_style(self, style: SubtitleStyle) -> None: ...
    def set_tracks_changed_callback(self, callback: Callable[[], None] | None) -> None: ...
    def set_state_changed_callback(self, callback: Callable[[], None] | None) -> None: ...
    def render_handle(self) -> object | None:
        """Opaque native handle for an in-scene video renderer (None for fakes)."""
        ...

    def shutdown(self) -> None: ...


@runtime_checkable
class DebridResolver(Protocol):
    """Later milestone: resolve an infoHash stream to a direct URL. Unused in MVP."""

    async def resolve(self, stream: Stream) -> str: ...


@runtime_checkable
class ExternalIdResolver(Protocol):
    async def resolve(self, source: str, external_id: str) -> ResolvedMedia: ...


@runtime_checkable
class SettingsStore(Protocol):
    """Durable store for user settings. load() must never raise on missing or
    corrupt data — it returns defaults instead."""

    def load(self) -> PersistedSettings: ...
    def save(self, settings: PersistedSettings) -> None: ...
