//! End to end: a real file, generated by the `ffmpeg` CLI, played through the
//! engine with the silent audio output. Skipped when `ffmpeg` is missing.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::{Arc, OnceLock};
use std::time::{Duration, Instant};

use gravitas_player_engine::{
    AudioBackend, Event, HardwareDecoding, LoadOptions, OwnRenderer, Player, RenderTarget,
    TrackKind,
};
use parking_lot::Mutex;

const WIDTH: u32 = 160;
const HEIGHT: u32 = 90;
const DURATION_S: f64 = 8.0;

/// A 160x90 test pattern with two audio tracks (English and German) and an
/// English subtitle track, made once per test run.
fn sample() -> Option<&'static Path> {
    static SAMPLE: OnceLock<Option<PathBuf>> = OnceLock::new();
    SAMPLE
        .get_or_init(|| {
            let dir =
                std::env::temp_dir().join(format!("gravitas-player-test-{}", std::process::id()));
            std::fs::create_dir_all(&dir).ok()?;
            let srt = dir.join("sample.srt");
            std::fs::write(&srt, "1\n00:00:01,000 --> 00:00:02,000\nhello\n").ok()?;
            let path = dir.join("sample.mkv");
            let status = Command::new("ffmpeg")
                .args(["-loglevel", "error", "-y"])
                .args([
                    "-f",
                    "lavfi",
                    "-i",
                    &format!("testsrc=size={WIDTH}x{HEIGHT}:rate=25:duration={DURATION_S}"),
                ])
                .args([
                    "-f",
                    "lavfi",
                    "-i",
                    &format!("sine=frequency=440:duration={DURATION_S}"),
                ])
                .args([
                    "-f",
                    "lavfi",
                    "-i",
                    &format!("sine=frequency=880:duration={DURATION_S}"),
                ])
                .arg("-i")
                .arg(&srt)
                .args(["-map", "0", "-map", "1", "-map", "2", "-map", "3"])
                .args(["-c:v", "mpeg4", "-q:v", "5", "-c:a", "mp2", "-c:s", "srt"])
                .args([
                    "-metadata:s:a:0",
                    "language=eng",
                    "-metadata:s:a:1",
                    "language=ger",
                ])
                .args(["-metadata:s:s:0", "language=eng"])
                .arg(&path)
                .status()
                .ok()?;
            status.success().then_some(path)
        })
        .as_deref()
}

struct Harness {
    player: Player,
    events: Arc<Mutex<Vec<Event>>>,
    pixels: Vec<u8>,
}

impl Harness {
    fn new() -> Self {
        Self::with_own_renderer(OwnRenderer::AtOnce)
    }

    fn with_own_renderer(own_renderer: OwnRenderer) -> Self {
        let events = Arc::new(Mutex::new(Vec::new()));
        let sink = {
            let events = events.clone();
            move |event: Event| events.lock().push(event)
        };
        let player = Player::with_own_renderer(AudioBackend::Null, sink, own_renderer)
            .expect("the player starts");
        Self {
            player,
            events,
            pixels: vec![0; (WIDTH * HEIGHT * 4) as usize],
        }
    }

    fn load(&self, url: &str, start: f64) {
        self.player
            .load(LoadOptions {
                url: url.to_owned(),
                start,
                audio_languages: vec!["ger".to_owned()],
                subtitle_languages: vec!["eng".to_owned()],
                ..LoadOptions::default()
            })
            .expect("load starts");
    }

    /// Renders like the QML item: every few milliseconds, whatever is due.
    fn render(&mut self) -> bool {
        let mut target = RenderTarget {
            pixels: &mut self.pixels,
            width: WIDTH,
            height: HEIGHT,
            stride: WIDTH as usize * 4,
        };
        self.player.render(&mut target).expect("render succeeds")
    }

    fn saw(&self, wanted: &Event) -> bool {
        self.events.lock().iter().any(|e| e == wanted)
    }

    /// Renders until `condition` holds, failing after `timeout`.
    fn until(
        &mut self,
        timeout: Duration,
        what: &str,
        mut condition: impl FnMut(&mut Self) -> bool,
    ) {
        let deadline = Instant::now() + timeout;
        while !condition(self) {
            assert!(
                Instant::now() < deadline,
                "timed out waiting for {what}; events: {:?}",
                self.events.lock()
            );
            self.render();
            std::thread::sleep(Duration::from_millis(5));
        }
    }
}

#[test]
fn a_file_opens_plays_seeks_and_ends() {
    let Some(sample) = sample() else {
        eprintln!("skipped: the ffmpeg CLI is not available to make a sample");
        return;
    };
    let mut h = Harness::new();
    h.load(sample.to_str().unwrap(), 0.0);
    h.until(Duration::from_secs(5), "the file to open", |h| {
        h.saw(&Event::FileLoaded)
    });

    let tracks = h.player.tracks();
    let count = |kind| tracks.iter().filter(|t| t.kind == kind).count();
    assert_eq!(
        (
            count(TrackKind::Video),
            count(TrackKind::Audio),
            count(TrackKind::Subtitle)
        ),
        (1, 2, 1)
    );
    assert_eq!(
        h.player.selected(TrackKind::Audio),
        Some(2),
        "German was preferred"
    );
    assert_eq!(h.player.selected(TrackKind::Subtitle), Some(1));
    let duration = h.player.duration().expect("a duration");
    assert!((duration - DURATION_S).abs() < 0.2, "duration {duration}");
    assert_eq!(h.player.video_size(), Some((WIDTH, HEIGHT)));

    // The first frame arrives, and time moves.
    h.until(Duration::from_secs(5), "the first frame", |h| {
        h.events
            .lock()
            .iter()
            .any(|e| matches!(e, Event::FirstFrame { .. }))
    });
    assert!(h.pixels.iter().any(|&b| b != 0), "the frame was drawn");
    let start = h.player.position();
    h.until(Duration::from_secs(5), "playback to advance", |h| {
        h.player.position() > start + 0.3
    });
    assert!(!h.player.is_loading());

    // Paused, the position holds.
    h.player.set_paused(true);
    let held = h.player.position();
    std::thread::sleep(Duration::from_millis(300));
    assert!((h.player.position() - held).abs() < 0.05);
    h.player.set_paused(false);

    // An exact seek lands where it was asked to.
    h.player.seek(5.0);
    h.until(Duration::from_secs(5), "the seek to settle", |h| {
        !h.player.is_loading()
    });
    let landed = h.player.position();
    assert!((5.0..5.6).contains(&landed), "landed at {landed}");

    // Switching audio keeps playing, from the same place.
    h.player.select(TrackKind::Audio, Some(1));
    assert_eq!(h.player.selected(TrackKind::Audio), Some(1));
    h.until(Duration::from_secs(5), "audio to resume", |h| {
        !h.player.is_loading()
    });
    let after = h.player.position();
    assert!((5.0..6.5).contains(&after), "switched at {after}");

    // And the file ends.
    h.until(Duration::from_secs(10), "the end of the file", |h| {
        h.saw(&Event::EndOfFile)
    });
    let end = h.player.position();
    assert!((end - duration).abs() < 0.5, "ended at {end}");
}

#[test]
fn a_file_resumes_at_its_start_position() {
    let Some(sample) = sample() else {
        return;
    };
    let mut h = Harness::new();
    h.load(sample.to_str().unwrap(), 4.0);
    // Until the file is open there is no duration to place the start in.
    assert!(h.player.position().abs() < f64::EPSILON || h.saw(&Event::FileLoaded));
    h.until(Duration::from_secs(5), "the first frame", |h| {
        h.events
            .lock()
            .iter()
            .any(|e| matches!(e, Event::FirstFrame { .. }))
    });
    let position = h.player.position();
    assert!((4.0..4.6).contains(&position), "resumed at {position}");
}

/// A player that expects to render zero-copy makes no device of its own --
/// and still draws when a frame comes through it after all: swscale at
/// once, the GPU renderer once the device it then starts is up.
#[test]
fn a_deferred_renderer_draws_when_a_frame_needs_it() {
    let Some(sample) = sample() else {
        eprintln!("skipped: no ffmpeg CLI to make a sample");
        return;
    };
    let mut h = Harness::with_own_renderer(OwnRenderer::WhenNeeded);
    // Zero-copy renders Dolby Vision, so a deferred renderer counts as one
    // that does -- unless GPU rendering is off.
    assert!(h.player.renders_dolby_vision());
    h.player.set_gpu_rendering(false);
    assert!(!h.player.renders_dolby_vision());
    h.player.set_gpu_rendering(true);
    h.load(sample.to_str().unwrap(), 0.0);
    h.until(Duration::from_secs(10), "a frame drawn", Harness::render);
}

#[test]
fn a_missing_file_fails_to_load() {
    let mut h = Harness::new();
    h.load("/nonexistent/gravitas/file.mkv", 0.0);
    h.until(Duration::from_secs(5), "the failure", |h| {
        h.events
            .lock()
            .iter()
            .any(|e| matches!(e, Event::LoadFailed(_)))
    });
    assert!(!h.player.is_loading());
}

#[test]
fn stopping_mid_playback_returns_promptly() {
    let Some(sample) = sample() else {
        return;
    };
    let mut h = Harness::new();
    h.load(sample.to_str().unwrap(), 0.0);
    h.until(Duration::from_secs(5), "the file to open", |h| {
        h.saw(&Event::FileLoaded)
    });
    let began = Instant::now();
    h.player.stop();
    assert!(
        began.elapsed() < Duration::from_secs(1),
        "stop took {:?}",
        began.elapsed()
    );
    assert!(h.player.tracks().is_empty());
}

#[test]
fn a_file_ends_even_when_nothing_renders() {
    // A hidden window draws nothing; the decoder must not stall on a full
    // frame queue, and the end must still be reported.
    let Some(sample) = sample() else {
        return;
    };
    let h = Harness::new();
    h.load(sample.to_str().unwrap(), DURATION_S - 2.0);
    let deadline = Instant::now() + Duration::from_secs(10);
    while !h.saw(&Event::EndOfFile) {
        assert!(
            Instant::now() < deadline,
            "no end of file; events: {:?}",
            h.events.lock()
        );
        std::thread::sleep(Duration::from_millis(20));
    }
}

/// Renders for `duration`, returning the last picture drawn.
fn settle(h: &mut Harness, duration: Duration) -> Vec<u8> {
    let deadline = Instant::now() + duration;
    while Instant::now() < deadline {
        h.render();
        std::thread::sleep(Duration::from_millis(5));
    }
    h.pixels.clone()
}

#[test]
fn subtitles_are_drawn_over_the_picture_and_hide_instantly() {
    let Some(sample) = sample() else {
        return;
    };
    let mut h = Harness::new();
    // Pictures are compared byte for byte, so they must all come from one
    // renderer: libplacebo starts in the background and would otherwise take
    // over between two of them on a loaded machine.
    h.player.set_gpu_rendering(false);
    // "hello" is on screen from 1s to 2s.
    h.load(sample.to_str().unwrap(), 1.3);
    h.player.set_paused(true);
    h.until(Duration::from_secs(5), "the first frame", |h| {
        h.events
            .lock()
            .iter()
            .any(|e| matches!(e, Event::FirstFrame { .. }))
    });
    let with = settle(&mut h, Duration::from_millis(400));
    h.player.set_subtitle_visible(false);
    assert!(
        h.player.wants_frames(),
        "a hidden subtitle needs a redraw while paused"
    );
    let without = settle(&mut h, Duration::from_millis(100));
    assert_ne!(with, without, "the subtitle changed the picture");
    h.player.set_subtitle_visible(true);
    let again = settle(&mut h, Duration::from_millis(100));
    assert_eq!(with, again, "showing it again draws the same subtitle");
}

#[test]
fn a_subtitle_file_becomes_a_track_of_its_own() {
    let Some(sample) = sample() else {
        return;
    };
    let srt = sample.with_file_name("addon.srt");
    std::fs::write(&srt, "1\n00:00:03,000 --> 00:00:05,000\nFROM AN ADDON\n").unwrap();
    let mut h = Harness::new();
    // One renderer for every picture compared, as above. On macOS
    // libplacebo's MoltenVK device came up between two of them in four runs
    // out of five.
    h.player.set_gpu_rendering(false);
    h.load(sample.to_str().unwrap(), 3.5);
    h.player.set_paused(true);
    h.until(Duration::from_secs(5), "the first frame", |h| {
        h.events
            .lock()
            .iter()
            .any(|e| matches!(e, Event::FirstFrame { .. }))
    });
    // Off the embedded track, so only the file can draw anything.
    h.player.select(TrackKind::Subtitle, None);
    let plain = settle(&mut h, Duration::from_millis(200));

    let id = h
        .player
        .add_subtitle(srt.to_str().unwrap(), "Addon", "eng", true)
        .expect("the file loads");
    assert_eq!(id, 2, "after the file's own track");
    let track = h
        .player
        .tracks()
        .into_iter()
        .find(|t| t.id == id && t.kind == TrackKind::Subtitle);
    assert!(track.is_some_and(|t| t.external && t.title.as_deref() == Some("Addon")));
    assert_eq!(h.player.selected(TrackKind::Subtitle), Some(id));
    let with_file = settle(&mut h, Duration::from_millis(200));
    assert_ne!(plain, with_file, "the file's subtitle is drawn");

    // A shift moves it out of the moment on screen.
    h.player.set_subtitle_delay(5.0);
    let shifted = settle(&mut h, Duration::from_millis(200));
    assert_eq!(plain, shifted);
    assert!((h.player.subtitle_delay() - 5.0).abs() < f64::EPSILON);
}

/// A file shaped like a mislabelled release: its default English subtitle
/// track says one line at the very end (a forced-only track without the
/// flag), and a second English track talks throughout.
fn quiet_default_sample() -> Option<PathBuf> {
    let base = sample()?;
    let dir = base.parent()?;
    let path = dir.join("quiet-default.mkv");
    if path.is_file() {
        return Some(path);
    }
    let quiet = dir.join("quiet.srt");
    std::fs::write(&quiet, "1\n00:00:07,500 --> 00:00:07,900\n[SIGN]\n").ok()?;
    let busy = dir.join("busy.srt");
    let mut text = String::new();
    for (n, tenth) in (0..70).step_by(5).enumerate() {
        let (s, e) = (tenth / 10, tenth % 10);
        let _ = write!(
            text,
            "{}\n00:00:0{s},{e}00 --> 00:00:0{s},{e}90\nline {n}\n\n",
            n + 1
        );
    }
    std::fs::write(&busy, text).ok()?;
    let status = Command::new("ffmpeg")
        .args(["-loglevel", "error", "-y", "-i"])
        .arg(base)
        .arg("-i")
        .arg(&quiet)
        .arg("-i")
        .arg(&busy)
        .args([
            "-map", "0:v", "-map", "0:a:0", "-map", "1", "-map", "2", "-c", "copy", "-c:s", "srt",
        ])
        .args([
            "-metadata:s:s:0",
            "language=eng",
            "-disposition:s:0",
            "default",
        ])
        .args(["-metadata:s:s:1", "language=eng", "-disposition:s:1", "0"])
        .arg(&path)
        .status()
        .ok()?;
    status.success().then_some(path)
}

#[test]
fn a_default_track_that_says_nothing_gives_way_to_one_that_talks() {
    let Some(sample) = quiet_default_sample() else {
        return;
    };
    let mut h = Harness::new();
    h.load(sample.to_str().unwrap(), 0.0);
    h.until(Duration::from_secs(5), "the switch", |h| {
        h.player.selected(TrackKind::Subtitle) == Some(2)
    });
    assert!(
        h.events
            .lock()
            .iter()
            .filter(|e| **e == Event::TracksChanged)
            .count()
            >= 2,
        "the switch is announced"
    );

    // Picked by hand, the quiet track stays picked.
    h.load(sample.to_str().unwrap(), 0.0);
    h.until(Duration::from_secs(5), "the file to open", |h| {
        h.player.duration().is_some()
    });
    h.player.select(TrackKind::Subtitle, Some(1));
    settle(&mut h, Duration::from_millis(600));
    assert_eq!(h.player.selected(TrackKind::Subtitle), Some(1));
}

/// The test pattern as H.264, which every hardware decoder takes.
fn h264_sample() -> Option<PathBuf> {
    let dir = sample()?.parent()?;
    let path = dir.join("h264.mkv");
    if path.is_file() {
        return Some(path);
    }
    let status = Command::new("ffmpeg")
        .args(["-loglevel", "error", "-y", "-f", "lavfi", "-i"])
        .arg(format!("testsrc=size={WIDTH}x{HEIGHT}:rate=25:duration=3"))
        .args(["-c:v", "libx264", "-pix_fmt", "yuv420p", "-crf", "10"])
        .arg(&path)
        .status()
        .ok()?;
    status.success().then_some(path)
}

/// The first picture of `sample` at 1s, decoded under `mode`, and the
/// hardware decoder that produced it. Drawn by libplacebo when `gpu` is set
/// and it comes up, else by swscale; None when libplacebo was asked for and
/// never came up.
fn first_picture(
    sample: &Path,
    mode: HardwareDecoding,
    gpu: bool,
) -> Option<(Vec<u8>, Option<String>)> {
    let mut h = Harness::new();
    // One renderer for every picture compared (see the subtitle test).
    h.player.set_gpu_rendering(gpu);
    if gpu {
        let deadline = Instant::now() + Duration::from_secs(10);
        while !h.player.renders_dolby_vision() {
            if Instant::now() > deadline {
                return None;
            }
            std::thread::sleep(Duration::from_millis(20));
        }
    }
    h.player.set_hardware_decoding(mode);
    h.player.set_paused(true);
    h.load(sample.to_str().unwrap(), 1.0);
    h.until(Duration::from_secs(5), "the first frame", |h| {
        h.events
            .lock()
            .iter()
            .any(|e| matches!(e, Event::FirstFrame { .. }))
    });
    let picture = settle(&mut h, Duration::from_millis(200));
    Some((picture, h.player.hardware_decoder()))
}

#[test]
fn a_device_that_does_not_exist_leaves_decoding_to_software() {
    let Some(sample) = h264_sample() else {
        return;
    };
    let only = HardwareDecoding::Only("no-such-device".to_owned());
    let (picture, decoder) = first_picture(&sample, only, false).unwrap();
    assert_eq!(decoder, None);
    assert!(picture.iter().any(|&b| b != 0), "the frame was drawn");
}

#[test]
fn hardware_decoding_off_decodes_in_software() {
    let Some(sample) = h264_sample() else {
        return;
    };
    let (picture, decoder) = first_picture(&sample, HardwareDecoding::Off, false).unwrap();
    assert_eq!(decoder, None);
    assert!(picture.iter().any(|&b| b != 0), "the frame was drawn");
}

/// On a machine with a hardware decoder, its frames come back to memory as
/// the same picture software decoding gives.
///
/// The decoded pixels are identical (NVDEC against libavcodec, checked with
/// the ffmpeg CLI), but they arrive as NV12 rather than yuv420p, and swscale
/// converts those two along different paths (mean difference 1.6/255,
/// measured). libplacebo samples both the same way, so the comparison is
/// drawn by it.
#[test]
fn hardware_decoded_frames_match_software_ones() {
    let Some(sample) = h264_sample() else {
        return;
    };
    let Some((hardware, decoder)) = first_picture(&sample, HardwareDecoding::Auto, true) else {
        eprintln!("skipped: libplacebo did not come up");
        return;
    };
    let Some(decoder) = decoder else {
        eprintln!("skipped: no hardware decoder here");
        return;
    };
    let (software, _) = first_picture(&sample, HardwareDecoding::Off, true).unwrap();
    // Rounding apart (measured: at most 1), the same picture.
    let max = software
        .iter()
        .zip(&hardware)
        .map(|(a, b)| a.abs_diff(*b))
        .max()
        .unwrap_or(0);
    eprintln!("decoded on {decoder}; largest difference {max}");
    assert!(max <= 2, "{decoder}: pixels differ by up to {max}");
}

/// The pitch of `samples` (interleaved, 48 kHz, first channel), from its
/// zero crossings; None when it is too quiet to tell.
fn pitch(samples: &[f32], channels: usize) -> Option<f64> {
    let mono: Vec<f32> = samples.iter().step_by(channels).copied().collect();
    let loud = mono.iter().filter(|s| s.abs() > 0.05).count();
    if mono.len() < 480 || loud < mono.len() / 2 {
        return None;
    }
    let crossings = mono
        .windows(2)
        .filter(|w| (w[0] < 0.0) != (w[1] < 0.0))
        .count();
    Some(crossings as f64 / 2.0 / (mono.len() as f64 / 48_000.0))
}

/// Renders until the output has played a tone near `hz` for its whole last
/// 100 ms; returns how long that took. Fails if playback reports loading on
/// the way: a switch must not stall anything.
fn until_heard(h: &mut Harness, hz: f64, timeout: Duration) -> Duration {
    let start = Instant::now();
    loop {
        let heard = pitch(&h.player.recent_output(), 2);
        if heard.is_some_and(|p| (p - hz).abs() < hz * 0.1) {
            return start.elapsed();
        }
        assert!(!h.player.is_loading(), "playback stalled for the switch");
        assert!(
            start.elapsed() < timeout,
            "never heard {hz} Hz; last pitch {heard:?}"
        );
        h.render();
        std::thread::sleep(Duration::from_millis(5));
    }
}

#[test]
fn switching_audio_is_heard_at_once_without_a_seek_or_a_stall() {
    let Some(sample) = sample() else {
        return;
    };
    let mut h = Harness::new();
    h.load(sample.to_str().unwrap(), 1.0);
    h.until(Duration::from_secs(5), "playback to run", |h| {
        h.player.position() > 1.5
    });
    // German (880 Hz) was preferred.
    until_heard(&mut h, 880.0, Duration::from_secs(2));
    // A seek would restart the timeline (preroll, a loading report, the
    // position held); a switch in place changes nothing but the sound.
    let before = h.player.position();
    h.player.select(TrackKind::Audio, Some(1));
    let took = until_heard(&mut h, 440.0, Duration::from_secs(1));
    eprintln!("the new track filled the last 100 ms of output after {took:?}");
    // 100 ms of the new tone fills the tap; anything much past that is the
    // switch itself.
    assert!(
        took < Duration::from_millis(350),
        "the switch took {took:?}"
    );
    let after = h.player.position();
    let elapsed = took.as_secs_f64();
    assert!(
        (after - before - elapsed).abs() < 0.25,
        "playback went on: {before} -> {after} in {elapsed} s"
    );
}

#[test]
fn switching_back_and_forth_ends_on_the_last_choice() {
    let Some(sample) = sample() else {
        return;
    };
    let mut h = Harness::new();
    h.load(sample.to_str().unwrap(), 1.0);
    h.until(Duration::from_secs(5), "playback to run", |h| {
        h.player.position() > 1.5
    });
    until_heard(&mut h, 880.0, Duration::from_secs(2));
    h.player.select(TrackKind::Audio, Some(1));
    settle(&mut h, Duration::from_millis(60));
    h.player.select(TrackKind::Audio, Some(2));
    settle(&mut h, Duration::from_millis(60));
    h.player.select(TrackKind::Audio, Some(1));
    until_heard(&mut h, 440.0, Duration::from_secs(1));
    assert_eq!(h.player.selected(TrackKind::Audio), Some(1));
}

#[test]
fn the_next_file_plays_after_a_switch_in_the_last() {
    let Some(sample) = sample() else {
        return;
    };
    let mut h = Harness::new();
    h.load(sample.to_str().unwrap(), 1.0);
    h.until(Duration::from_secs(5), "playback to run", |h| {
        h.player.position() > 1.5
    });
    until_heard(&mut h, 880.0, Duration::from_secs(2));
    h.player.select(TrackKind::Audio, Some(1));
    until_heard(&mut h, 440.0, Duration::from_secs(1));
    // A new file starts on its own first selection: the switches made in
    // the last one must not mark all of its audio as stale, which held the
    // clock at the start position behind a spinner for good.
    h.load(sample.to_str().unwrap(), 1.0);
    h.until(Duration::from_secs(5), "the next file to play", |h| {
        h.player.position() > 2.0
    });
    until_heard(&mut h, 880.0, Duration::from_secs(2));
}

#[test]
fn a_switch_while_paused_is_what_plays_on_resume() {
    let Some(sample) = sample() else {
        return;
    };
    let mut h = Harness::new();
    h.load(sample.to_str().unwrap(), 1.0);
    h.until(Duration::from_secs(5), "playback to run", |h| {
        h.player.position() > 1.5
    });
    until_heard(&mut h, 880.0, Duration::from_secs(2));
    h.player.set_paused(true);
    let held = h.player.position();
    h.player.select(TrackKind::Audio, Some(1));
    settle(&mut h, Duration::from_millis(200));
    assert!(
        (h.player.position() - held).abs() < 0.05,
        "paused means held"
    );
    h.player.set_paused(false);
    let took = until_heard(&mut h, 440.0, Duration::from_secs(1));
    assert!(took < Duration::from_millis(350), "resumed after {took:?}");
}

/// An HEVC 10-bit file tagged PQ, with a 5.1 AAC track: what the player's
/// format badges are read from. None without the ffmpeg CLI or libx265.
fn hdr_sample() -> Option<&'static Path> {
    static SAMPLE: OnceLock<Option<PathBuf>> = OnceLock::new();
    SAMPLE
        .get_or_init(|| {
            let dir =
                std::env::temp_dir().join(format!("gravitas-hdr-test-{}", std::process::id()));
            std::fs::create_dir_all(&dir).ok()?;
            let path = dir.join("hdr10.mkv");
            let status = Command::new("ffmpeg")
                .args(["-loglevel", "error", "-y", "-f", "lavfi", "-i"])
                // Tagged on the frames: the encoder takes its colour tags
                // from them, and ffmpeg's own -color_* flags alone left the
                // stream untagged.
                .arg(
                    "testsrc2=size=320x180:rate=25:duration=2,setparams=color_trc=smpte2084:\
                     color_primaries=bt2020:colorspace=bt2020nc:range=tv",
                )
                .args(["-f", "lavfi", "-i", "sine=frequency=440:duration=2"])
                .args(["-c:v", "libx265", "-pix_fmt", "yuv420p10le"])
                .args(["-x265-params", "log-level=error"])
                .args(["-c:a", "aac", "-ac", "6"])
                .arg(&path)
                .status()
                .ok()?;
            status.success().then_some(path)
        })
        .as_deref()
}

#[test]
fn tracks_say_what_the_file_is() {
    let Some(sample) = hdr_sample() else {
        eprintln!("skipped: no ffmpeg CLI with libx265 to make an HDR sample");
        return;
    };
    let mut h = Harness::new();
    h.load(sample.to_str().unwrap(), 0.0);
    h.until(Duration::from_secs(5), "the file to open", |h| {
        h.saw(&Event::FileLoaded)
    });
    let tracks = h.player.tracks();
    let video = tracks
        .iter()
        .find(|t| t.kind == TrackKind::Video)
        .expect("a video track");
    assert_eq!(video.transfer, Some("pq"));
    assert_eq!(video.dolby_vision_profile, None);
    let audio = tracks
        .iter()
        .find(|t| t.kind == TrackKind::Audio)
        .expect("an audio track");
    assert_eq!(audio.channels, Some(6));
    assert_eq!(audio.transfer, None);
    // The profile comes from the decoder once it runs, whatever the header
    // said (a header often does not, since the engine opens files without
    // FFmpeg's full probe).
    h.until(Duration::from_secs(5), "the audio decoder's profile", |h| {
        h.player.audio_profile().is_some()
    });
    assert_eq!(h.player.audio_profile().as_deref(), Some("LC"));
    // Nothing in this file carries HDR10+ metadata.
    h.until(Duration::from_secs(5), "the first frame", |h| {
        h.events
            .lock()
            .iter()
            .any(|e| matches!(e, Event::FirstFrame { .. }))
    });
    assert!(!h.player.hdr10_plus());
}

#[test]
fn a_keyframe_start_begins_at_the_keyframe_before_the_point() {
    let Some(sample) = sample() else {
        return;
    };
    let first_frame = |h: &mut Harness| {
        h.until(Duration::from_secs(5), "the first frame", |h| {
            h.events
                .lock()
                .iter()
                .any(|e| matches!(e, Event::FirstFrame { .. }))
        });
        h.player.position()
    };
    let mut exact = Harness::new();
    exact.player.set_paused(true);
    exact.load(sample.to_str().unwrap(), 3.7);
    let landed = first_frame(&mut exact);
    assert!(
        (3.7..3.8).contains(&landed),
        "an exact start lands at 3.7, not {landed}"
    );

    let mut keyframe = Harness::new();
    keyframe.player.set_paused(true);
    keyframe
        .player
        .load(LoadOptions {
            url: sample.to_str().unwrap().to_owned(),
            start: 3.7,
            keyframe_start: true,
            ..LoadOptions::default()
        })
        .expect("load starts");
    let landed = first_frame(&mut keyframe);
    // mpeg4 at its default twelve-frame interval: a keyframe every 0.48s.
    assert!(
        (3.7 - 0.5..3.7).contains(&landed),
        "a keyframe start lands just before 3.7, not {landed}"
    );
}
